<a href="https://colab.research.google.com/github/hxtruong/ai-vietnam-summer-2019/blob/master/week_5/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
# create array
l = list(range(1,5))
# create nd-array
data = np.array(l)

print(data)
print(data[0])
print(data[3])

[1 2 3 4]
1
4


![result](https://raw.githubusercontent.com/hxtruong/ai-vietnam-summer-2019/master/week_5/chap5_np_1.png)

In [6]:
print(type(data))
print(type(data[[0]]))
print(data.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4,)


In [15]:
# Change shape of array
arr1 = np.arange(12)
print(arr1)
print(arr1.shape)

arr2 = arr1.reshape((3,4))
print(arr2)
print(arr2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [18]:
# type of data
print(arr1.dtype)
arr3 = np.array([2.3, 5.2])
print(arr3)
print(arr3.dtype)

int64
[2.3 5.2]
float64


In [21]:
# assign data for array
arr4 = np.arange(15)
print(arr4)
arr4[9] = 99999
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[    0     1     2     3     4     5     6     7     8 99999    10    11
    12    13    14]


In [31]:
arr5 = np.zeros((4,5))
print(arr5)
arr6 = np.ones((3,4))
print(arr6)
arr7 = np.full((2,3), 33)
print(arr7)
arr8 = np.eye(4)
print(arr8)
print(np.random.random((2,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[33 33 33]
 [33 33 33]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.54022669 0.11788345 0.07432315]
 [0.97978526 0.09068111 0.60444076]]


In [35]:
# condition for array
arr = np.arange(10)
out = np.where(arr < 5, arr, 10*arr)
print(out)

[ 0  1  2  3  4 50 60 70 80 90]


In [36]:
# flat array to 1-D array
arr = np.array([[4,5], [2,3]])
out = arr.flatten()
print(arr)
print(out)

[[4 5]
 [2 3]]
[4 5 2 3]


In [38]:
# Slice 2D- array
a_arr = np.array([[1,2,3],[4,5,6]])
print(a_arr)
print("-----------")
# Slice 2d array like 1d array
b_arr = a_arr[:, 1:3]
print(b_arr)


[[1 2 3]
 [4 5 6]]
-----------
[[2 3]
 [5 6]]


![alt text](https://raw.githubusercontent.com/hxtruong/ai-vietnam-summer-2019/master/week_5/chap5_np_9.png)