<a href="https://colab.research.google.com/github/hxtruong/ai-vietnam-summer-2019/blob/master/week_5/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy** is library of python to support in calculate on array, vector or matrix

> **Ref:** https://aivietnam.ai/courses/aisummer2019/lessons/gioi-thieu-ve-numpy/


In [0]:
import numpy as np
# create array
l = list(range(1,5))
# create nd-array
data = np.array(l)

print(data)
print(data[0])
print(data[3])

[1 2 3 4]
1
4


![result](https://raw.githubusercontent.com/hxtruong/ai-vietnam-summer-2019/master/week_5/chap5_np_1.png)

In [0]:
print(type(data))
print(type(data[[0]]))
print(data.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(4,)


In [0]:
# Change shape of array
arr1 = np.arange(12)
print(arr1)
print(arr1.shape)

arr2 = arr1.reshape((3,4))
print(arr2)
print(arr2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [0]:
# type of data
print(arr1.dtype)
arr3 = np.array([2.3, 5.2])
print(arr3)
print(arr3.dtype)

int64
[2.3 5.2]
float64


In [0]:
# assign data for array
arr4 = np.arange(15)
print(arr4)
arr4[9] = 99999
print(arr4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[    0     1     2     3     4     5     6     7     8 99999    10    11
    12    13    14]


In [0]:
arr5 = np.zeros((4,5))
print(arr5)
arr6 = np.ones((3,4))
print(arr6)
arr7 = np.full((2,3), 33)
print(arr7)
arr8 = np.eye(4)
print(arr8)
print(np.random.random((2,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[33 33 33]
 [33 33 33]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.54022669 0.11788345 0.07432315]
 [0.97978526 0.09068111 0.60444076]]


In [0]:
# condition for array
arr = np.arange(10)
out = np.where(arr < 5, arr, 10*arr)
print(out)

[ 0  1  2  3  4 50 60 70 80 90]


In [0]:
# flat array to 1-D array
arr = np.array([[4,5], [2,3]])
out = arr.flatten()
print(arr)
print(out)

[[4 5]
 [2 3]]
[4 5 2 3]


In [0]:
# Slice 2D- array
a_arr = np.array([[1,2,3],[4,5,6]])
print(a_arr)
print("-----------")
# Slice 2d array like 1d array
b_arr = a_arr[:, 1:3]
print(b_arr)


[[1 2 3]
 [4 5 6]]
-----------
[[2 3]
 [5 6]]


![alt text](https://raw.githubusercontent.com/hxtruong/ai-vietnam-summer-2019/master/week_5/chap5_np_9.png)

> The sliced array has same address with the original array. So, if one array is changed value, the other value array will be modified

In [0]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# decrease dimension
row_r1 = arr[1, :]
print(row_r1, row_r1.shape)

# keep the dimension
row_r2 = arr[1:2, :]
print(row_r2, row_r2.shape)

[4 5 6] (3,)
[[4 5 6]] (1, 3)
[6 7 8 9]


In [0]:
print(arr)
bool_idx = arr > 5
print("Check element is greater 5: ")
print(bool_idx)
print(arr[bool_idx])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Check element is greater 5: 
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


### Operation on array

In [0]:
x = np.array([10,2,13,4], dtype=np.float64)
y = np.array([5,36,7,18], dtype=np.float64)
print("X: ", x)
print("Y: ", y)
# Sum of 2 arrays
print("Sum of 2 array: ")
print(x+y)
print(np.add(x,y))

X:  [10.  2. 13.  4.]
Y:  [ 5. 36.  7. 18.]
Sum of 2 array: 
[15. 38. 20. 22.]
[15. 38. 20. 22.]


In [0]:
print("Subtract two array: ")
print(x-y)
print(np.subtract(x,y))

Subtract two array: 
[  5. -34.   6. -14.]
[  5. -34.   6. -14.]


In [0]:
print("Multiple 2 array: ")
print(x*y)
print(np.multiply(x,y))

Multiple 2 array: 
[50. 72. 91. 72.]
[50. 72. 91. 72.]


In [0]:
print("Divide two array: ")
print(x/y)
print(np.divide(x,y))

Divide two array: 
[2.         0.05555556 1.85714286 0.22222222]
[2.         0.05555556 1.85714286 0.22222222]


In [0]:
print("X: ", x)
print("Trunc of element in array: ")
print(np.sqrt(x))

X:  [10.  2. 13.  4.]
Trunc of element in array: 
[3.16227766 1.41421356 3.60555128 2.        ]


#### Vector & matrix

In [0]:
v = np.array([3,2])
w = np.array([5,8])
X = np.array([[1,2],[10,2]])

In [0]:
print("Inner product between 2 vector: ")
print(v.dot(w))
print(np.dot(v,w))

Inner product between 2 vector: 
31
31


In [0]:
# Multiply vector & matrix
print("v: ", v)
print("X: \n", X)
print("------------------------------")
print("X.dot(v): ", X.dot(v))
print("v.dot(X): ", v.dot(X))

v:  [3 2]
X: 
 [[ 1  2]
 [10  2]]
------------------------------
X.dot(v):  [ 7 34]
v.dot(X):  [23 10]


In [0]:
# Multiply 2 matrix
Y = np.array([[1,3], [4,2]])
print("X: \n", X)
print("Y: \n", Y)
print("------------------------------")
print("X.dot(Y): \n", X.dot(Y))
print("Y.dot(X): \n", Y.dot(X))

X: 
 [[ 1  2]
 [10  2]]
Y: 
 [[1 3]
 [4 2]]
------------------------------
X.dot(Y): 
 [[ 9  7]
 [18 34]]
Y.dot(X): 
 [[31  8]
 [24 12]]


#### Sum of array

In [0]:
# Sum
print("X: ", X)
print("Sum: \n", np.sum(X))
print("Sum row: \n", np.sum(X, axis=1))
print("Sum columns: \n", np.sum(X, axis=0))

X:  [[ 1  2]
 [10  2]]
Sum: 
 15
Sum rows: 
 [ 3 12]
Sum columns: 
 [11  4]


#### Transposaed matrix

In [0]:
print("X: \n", X)
print("=> X.T: \n", X.T)

X: 
 [[ 1  2]
 [10  2]]
=> X.T: 
 [[ 1 10]
 [ 2  2]]


#### Broadcasting

In [0]:
X = np.arange(1,13)
X = np.reshape(X, (4,3))
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
v = np.array([1,0,1])

Problem is how to adding two array which on array has different size( dimension). 
> Solution: make the less size array become the same size like the other one. Then adding two array.

In [0]:
V_t = np.tile(v, (4,1))
V_t

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [0]:
# Calculate sum
X + V_t

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [0]:
# In numpy, is will auto calculate: 
X + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

It is called **broadcasting**![alt text](https://raw.githubusercontent.com/hxtruong/ai-vietnam-summer-2019/master/week_5/chap5_np_32-768x608.png)